-- 버스 예약 시스템

-- 버스(BUS) 테이블
CREATE TABLE BUS(
	BUS_NO NUMBER CONSTRAINT BUS_PK PRIMARY KEY,
	-- CONSTRAINT (제약 조건) 뒤에 제약 조건명
	-- PRIMARY KEY : NOT NULL + UNIQUE
	BUS_DEPARTURES VARCHAR2(30) NOT NULL,
	-- 출발지 NULL 이면 안됨
	BUS_ARRIVALS VARCHAR2(30) NOT NULL,
	-- 도착지 NULL 이면 안됨
	BUS_DEPARTURE_TIME VARCHAR(10) NOT NULL,
	BUS_ARRIVAL_TIME VARCHAR(10) NOT NULL
);
-- 중간에 , 안 찍어서 누락된 우괄호 ERROR 발생

COMMENT ON COLUMN BUS.BUS_NO IS '버스번호(시퀀스 SEQ_BUS_NO)';
-- 5000번부터 시작
COMMENT ON COLUMN BUS.BUS_DEPARTURES IS '출발지';
COMMENT ON COLUMN BUS.BUS_ARRIVALS IS '도착지';
COMMENT ON COLUMN BUS.BUS_DEPARTURE_TIME IS '출발시간';
COMMENT ON COLUMN BUS.BUS_ARRIVAL_TIME IS '도착시간';

-- 각 버스의 좌석 정보 테이블
CREATE TABLE BUS_SEAT (
	BUS_NO NUMBER REFERENCES BUS ON DELETE CASCADE,
	-- 버스 테이블 BUS_NO 삭제시 같이 삭제 및 외래키로 참조
	SEAT_NO NUMBER NOT NULL,
	-- 좌석 개수 45개
	SEAT_RESERVATION CHAR(1) DEFAULT 'N' CHECK( SEAT_RESERVATION IN ('Y', 'N'))
	-- CHECK 제약 조건 : 컬럼에 기록되는 값에 조건 설정을 할 수 있음
	-- CHECK (컬럼명 비교연산자 비교값)
	-- ex) CHECK(GENDER IN ('남', '여'))
);

COMMENT ON COLUMN BUS_SEAT.BUS_NO IS '버스번호(BUS테이블참조)';
COMMENT ON COLUMN BUS_SEAT.SEAT_NO IS '좌석번호(1~45)';
-- 1씩 증가해서 45까지
COMMENT ON COLUMN BUS_SEAT.SEAT_RESERVATION IS '좌석예약상태(Y/N)';

-- SEQUENCE 생성 (BUS_NO) 5000 부터 1씩 증가 
CREATE SEQUENCE SEQ_BUS_NO
START WITH 5000
NOCACHE;

-- 버스 서울 -> 강원도 5개 INSERT
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '강원도', '06:45', '08:15');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '강원도', '08:45', '10:30');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '강원도', '10:50', '13:05');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '강원도', '15:50', '18:15');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '강원도', '19:15', '22:00');

-- 버스 서울 -> 부산 3개 INSERT
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '부산', '05:15', '10:00');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '부산', '09:55', '14:00');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '부산', '15:05', '20:45');

-- 버스 서울 -> 광주 3개 INSERT
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '광주', '12:00', '16:30');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '광주', '15:35', '19:55');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '광주', '18:05', '22:45');

-- 버스 서울 -> 대전 5개 INSERT
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '대전', '07:05', '09:35');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '대전', '08:30', '10:50');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '대전', '11:20', '13:45');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '대전', '18:35', '21:20');
INSERT INTO BUS
VALUES(SEQ_BUS_NO.NEXTVAL, '서울', '대전', '19:00', '22:45');

SELECT * FROM BUS;
COMMIT;

-- 반복문
BEGIN
	FOR I IN 5000..5015
	LOOP
		FOR J IN 1..45
		LOOP
			INSERT INTO BUS_SEAT VALUES (I,J,DEFAULT);
		END LOOP;
	END LOOP;
END;

SELECT * FROM BUS_SEAT;
COMMIT;

-- 예약한 사람 테이블
CREATE TABLE RESERVE_PERSON(
	NAME VARCHAR2(10) NOT NULL,
	PHONE CHAR(11) PRIMARY KEY,
	BUS_DEPARTURES VARCHAR2(30),
	BUS_ARRIVALS VARCHAR2(30),
	BUS_DEPARTURE_TIME VARCHAR(10),
	BUS_NO NUMBER REFERENCES BUS ON DELETE CASCADE,
	SEAT_NO NUMBER
);

SELECT * FROM RESERVE_PERSON;
COMMIT;

-- 버스 예약한 회원 으로 받고
-- 아이디 패스워드도